device: cuda

model_path: models
storage:
  gt_path: image_features
runtime:
  default:
    fps: 4
    ipt_rgb: true
    allow_single_frame: false
    thres: 0.55
    content_id: null
    ground_truth: IBC