device: cuda

storage:
  model_path: /ml/models/celeb
  gt_path: /ml/models/celeb/image_features
container:
  model_path: models
  gt_path: models/image_features
ground_truth:
  url: https://tagging.ai.contentfabric.io/ground-truth