device: cuda

storage:
  model_path: /ml/models/celeb
  gt_path: /ml/models/celeb/image_features
container:
  model_path: models 
  gt_path: models/image_features
runtime:
  default:
    fps: 4
    ipt_rgb: true
    allow_single_frame: false
    candidates: 10
    min_box_size: 0.005
    gamma: 10
    thres: 0.325
    content_id: null
    restrict_list: null
    ground_truth: IBC