device: cuda

storage:
  model_path: /eluvio/ml/models/celeb
  gt_path: /eluvio/ml/models/celeb/image_features
container:
  model_path: models 
  gt_path: models/image_features
runtime:
  default:
    fps: 4
    ipt_rgb: true
    allow_single_frame: false
    candidates: 5
    min_box_size: 0.005
    thres: 0.4
    extra_thres: 0.28
    content_id: null
    restrict_list: null
    ground_truth: IBC